-- MySQL Script generated by MySQL Workbench
-- 01/19/17 23:24:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(25) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_employed` TINYINT(1) NOT NULL DEFAULT 0,
  `user_consumption` DOUBLE NULL,
  `user_timestamp` DATETIME NULL,
  `user_token` INT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order_list` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order_list` (
  `order_list_id` INT NOT NULL AUTO_INCREMENT,
  `order_list_is_settled` TINYINT(1) NOT NULL DEFAULT 0,
  `order_list_cost` DECIMAL NULL,
  `order_list_note` VARCHAR(255) NULL,
  `order_list_asked_bill` TINYINT(1) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`order_list_id`, `user_id`),
  INDEX `fk_Order_list_Users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Order_list_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Menu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_cost` INT NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `product_description` VARCHAR(255) NULL,
  `product_quantity` VARCHAR(45) NULL,
  `product_type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `order_id` INT NOT NULL,
  `order_list_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `product_amount` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`order_id`, `order_list_id`),
  INDEX `fk_Order_Order_list1_idx` (`order_list_id` ASC),
  INDEX `fk_Order_Menu1_idx` (`product_id` ASC),
  CONSTRAINT `fk_Order_Order_list1`
    FOREIGN KEY (`order_list_id`)
    REFERENCES `mydb`.`Order_list` (`order_list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Menu1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Menu` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
